import './globals.css'

import type { Metadata } from 'next'

import { Toaster } from '@/components/ui/toaster'

import { JwtProvider } from '@/context/jwt-context'
import { ThemeProvider } from '@/components/theme/theme-provider'
import { ApolloClientProvider } from '@/context/apollo-wrapper'

import {
  Inter,
  Roboto_Flex as Roboto,
  Bai_Jamjuree as BaiJamjuree,
} from 'next/font/google'

interface RootLayoutProps {
  children: React.ReactNode
}

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const roboto = Roboto({
  subsets: ['latin'],
  variable: '--font-roboto',
})

const baiJamjuree = BaiJamjuree({
  subsets: ['latin'],
  weight: '700',
  variable: '--font-bai-jamjuree',
})

export const metadata: Metadata = {
  title: 'Nexus Erp Web',
  description: 'Generated by create next app',
  icons: {
    icon: ['/favicon.ico'],
    apple: ['/apple-touch-icon.png'],
    shortcut: ['/apple-touch-icon.png'],
  },
  manifest: '/site.webmanifest',
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt-BR">
      <body
        suppressHydrationWarning={true}
        className={`${roboto.variable} ${baiJamjuree.variable} ${inter.variable}`}
      >
        <ApolloClientProvider>
          <JwtProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <Toaster />
              {children}
            </ThemeProvider>
          </JwtProvider>
        </ApolloClientProvider>
      </body>
    </html>
  )
}
